### PR TITLE
task: implement DisplayMarkdown

### PR DESCRIPTION
**Pull request by rgimen3z**
Also added an example to the Users table. 
Addresses: https://github.com/pydantic/FastUI/issues/248

### CODE REVIEW

**Comment by rgimen3z** [comment]
cc: @sydney-runkle since I saw you organizing and merging PRs recently (thanks for spending some time focused on FastUI!)

**Comment by rgimen3z** [comment]
> cc: @sydney-runkle since I saw you organizing and merging PRs recently (thanks for spending some time focused on FastUI!)

@sydney-runkle any chance we can get this reviewed (and merged) sooner rather than later? Thanks

**Review by sydney-runkle — APPROVED** [review]
@rgimen3z,

Awesome work here. Apologies for the delay in reviewing!

**Comment by Dragon-GCS** [comment]
It appears that this issue has not been fully resolved. On the demo page, the 'Status' column is not being correctly rendered as Markdown.
image

**Comment by rgimen3z** [comment]
> It appears that this issue has not been fully resolved. On the demo page, the 'Status' column is not being correctly rendered as Markdown. image

I _believe_ this is because FastUI's front-end code hasn't been deployed in over 2 months? @sydney-runkle are there plans to deploy following some sort of cadence?

**Pull request merged**
