### PR TITLE
Update README.md with Railway deploy button

### PR DESCRIPTION
**Pull request by PaulLockett**
This adds a Railway deploy button for this project so new users can use it right away and gtfol.

### CODE REVIEW

**Comment by hramezani** [comment]
Thanks @PaulLockett for this PR.

What does this button do? what does Railway use for?

**Comment by hramezani** [comment]
@samuelcolvin do we want to include this button?

**Comment by PaulLockett** [comment]
hey @hramezani This button lets a user deploy the basic fast UI server that is the example in the read me.

Railway is basically a managed kube cluster with a web gui.

I made a Railway template for FastUI so people can spin up a server for it at the click of a button the same way that vercel allows web devs to do.

See the template I made here: https://github.com/PaulLockett/FastUI_Template

**Comment by PaulLockett** [comment]
full disclosure If a user uses my template pass the free trial on railway I get a kick back of credits with railway to host my own servers and databases.

**Comment by PaulLockett** [comment]
@hramezani @samuelcolvin  any updates here?

**Comment by samuelcolvin** [comment]
Sorry for the slow reply. I don't think this makes sense since no one would want to deploy the demo directly.

**Pull request closed without merging**
